name: trait_document_scanner_android
description: Android implementation of the trait_document_scanner plugin
repository: https://github.com/criistian14/flutter_document_scanner/tree/master/flutter_document_scanner_android
version: 1.1.1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: trait_document_scanner
    platforms:
      android:
        package: com.christian.traitDocumentScanner
        pluginClass: TraitDocumentScannerPlugin
        dartPluginClass: TraitDocumentScannerAndroid

dependencies:
  flutter:
    sdk: flutter
  trait_document_scanner_platform_interface:
    path: ../trait_document_scanner_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
