name: trait_document_scanner_example
description: Demonstrates how to use the trait_document_scanner plugin.
version: 0.5.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  trait_document_scanner:
    # When depending on this package from a real application you should use:
    #   trait_document_scanner: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    git:
      url: git@github.com:stanojevicboban/flutter_document_scanner.git
      path: trait_document_scanner
      ref: "trait-version"
  image_picker: ^1.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
